---
- name: Challenge 16 - GRE over IPsec
  hosts: vmx
  connection: netconf
  gather_facts: no

  tasks:
    - name: IPsec security proposal
      junipernetworks.junos.junos_config:
        lines:
          - set security ipsec proposal GRE-PROP protocol esp
          - set security ipsec proposal GRE-PROP encryption-algorithm aes-128-cbc
          - set security ipsec proposal GRE-PROP authentication-algorithm hmac-sha1-96

    - name: IPsec security proposal
      junipernetworks.junos.junos_config:
        lines:
          - set security ipsec policy GRE-POL proposals GRE-PROP

    - name: IPsec VPN (transport mode) vMX1
      junipernetworks.junos.junos_config:
        lines:
          - set security ipsec vpn GRE-VPN1 bind-interface st0.0
          - set security ipsec vpn GRE-VPN1 ike gateway GW-GRE
          - set security ipsec vpn GRE-VPN1 ipsec-policy GRE-POL
          - set security ipsec vpn GRE-VPN1 establish-tunnels immediately
     when: inventory_hostname == 'vMX1'

    - name: IPsec VPN (transport mode) vMX2
      junipernetworks.junos.junos_config:
        lines:
          - set security ipsec vpn GRE-VPN2 bind-interface st0.0
          - set security ipsec vpn GRE-VPN2 ike gateway GW-GRE
          - set security ipsec vpn GRE-VPN2 ipsec-policy GRE-POL
          - set security ipsec vpn GRE-VPN2 establish-tunnels immediately
     when: inventory_hostname == 'vMX2'

    - name: IKE gateway VMX1
      junipernetworks.junos.junos_config:
        lines:
          - set security ike policy IKE-GRE mode main
          - set security ike policy IKE-GRE proposal-set standard
          - set security ike policy IKE-GRE pre-shared-key ascii-text mysecret123
          - set security ike gateway GW-GRE address 192.168.1.1
          - set security ike gateway GW-GRE external-interface ge-0/0/0
          - set security ike gateway GW-GRE ike-policy IKE-GRE
     when: inventory_hostname == 'vMX1'

    - name: IKE gateway VMX2
      junipernetworks.junos.junos_config:
        lines:
          - set security ike policy IKE-GRE mode main
          - set security ike policy IKE-GRE proposal-set standard
          - set security ike policy IKE-GRE pre-shared-key ascii-text mysecret123
          - set security ike gateway GW-GRE address 192.168.1.2
          - set security ike gateway GW-GRE external-interface ge-0/0/0
          - set security ike gateway GW-GRE ike-policy IKE-GRE
     when: inventory_hostname == 'vMX2'

    - name: Static route to GRE tunnel
      junipernetworks.junos.junos_config:
        lines:
          - set routing-options static route 10.10.10.0/30 next-hop st0.0
