---
- name: Challenge 9 - OSPF interface types
  hosts: all
  connection: netconf
  gather_facts: no

  tasks:

    - name: Configure Point-to-Point OSPF interface
      junipernetworks.junos.junos_config:
        lines:
          - delete protocols ospf area 1 interface ge-0/0/1.0
          - set protocols ospf area 0 interface ge-0/0/1.0 interface-type p2p
      when: inventory_hostname in ['vMX1', 'vQFX1']

    - name: Configure NMBA OSPF interface
      junipernetworks.junos.junos_config:
        lines:
          - delete protocols ospf area 1 interface ge-0/0/2.0
          - set protocols ospf area 0 interface ge-0/0/2.0 interface-type nbma
      when: inventory_hostname == 'vMX1'
    
    - name: Configure interfaces
      junipernetworks.junos.junos_config:
        lines:
          - set interfaces ge-0/0/1.0 family inet address 172.10.10.1/30
      when: inventory_hostname == 'vMX1'

    - name: Configure interfaces
      junipernetworks.junos.junos_config:
        lines:
          - set interfaces xe-0/0/3.0 family inet address 172.10.10.2/30
      when: inventory_hostname == 'vQFX1'

    - name: Configure interfaces
      junipernetworks.junos.junos_config:
        lines:
          - set interfaces ge-0/0/1.0 family inet address 172.10.11.1/30
      when: inventory_hostname == 'vMX2'

    - name: Configure interfaces
      junipernetworks.junos.junos_config:
        lines:
          - set interfaces xe-0/0/3.0 family inet address 172.10.11.2/30
      when: inventory_hostname == 'vQFX2'
