---
- name: Challenge 10 -  IS-IS Basics and DIS Election
  hosts: vmx
  connection: netconf
  gather_facts: no

  tasks:

    - name: Configure IS-IS on ge-0/0/2.0
      junipernetworks.junos.junos_config:
        lines:
          - set routing-options router-id 1.1.1.1
          - set protocols isis level 1 disable
          - set protocols isis level 2 wide-metrics-only
          - set protocols isis interface lo0.0
          - set protocols isis interface ge-0/0/2.0 level 2
          - set protocols isis interface ge-0/0/2.0
      when: inventory_hostname == 'vMX1'
