---
- name: Challenge 9 - OSPF interface types
  hosts: all
  connection: netconf
  gather_facts: no

  tasks:

    - name: Configure Point-to-Point OSPF interface
      junipernetworks.junos.junos_config:
        lines:
          - set protocols ospf area 1 interface ge-0/0/1.0 interface-type p2p
      when: inventory_hostname in ['vMX1', 'vQFX1']

    - name: Configure Non-Broadcast OSPF interface
      junipernetworks.junos.junos_config:
        lines:
          - set protocols ospf area 1 interface ge-0/0/2.0 interface-type nbma
      when: inventory_hostname == 'vMX1'
