---
- name: Challenge 10 -  IS-IS Basics and DIS Election
  hosts: vmx
  connection: netconf
  gather_facts: no

  tasks:

    - name: minimal ISIS setup
      junipernetworks.junos.junos_config:
        lines:
          - set protocols isis net 49.0001.0100.0000.0001.00
          - set protocols isis interface ge-0/0/2.0
      when: inventory_hostname == 'vMX1'
