---
- name: Challenge 10 -  IS-IS Basics and DIS Election
  hosts: vmx
  connection: netconf
  gather_facts: no

  tasks:

    - name: Configure IS-IS on ge-0/0/3.0 and lo0.0
      junipernetworks.junos.junos_config:
        lines:
          - set protocols interface ge-0/0/3.0
          - set protocols isis interface lo0.0 passive
          - set protocols isis level 1 disable
          - set protocols isis level 2 wide-metrics-only
          - set protocols isis family inet unicast
          - set protocols isis interface ge-0/0/3.0 point-to-point
          - set protocols isis interface ge-0/0/3.0 level 2
