---
all:
  children:
    vmx:
      hosts:
        PE1:
          ansible_host: 192.168.100.11
          ansible_user: lab
          ansible_password: lab123
          ansible_network_os: junipernetworks.junos.junos
          ansible_connection: netconf
          loopback_ip: 1.1.1.1
        PE2:
          ansible_host: 192.168.100.12
          ansible_user: lab
          ansible_password: lab123
          ansible_network_os: junipernetworks.junos.junos
          ansible_connection: netconf
          loopback_ip: 2.2.2.2

    vqfx:
      hosts:
        vQFX1:
          ansible_host: 192.168.100.21
          ansible_user: lab
          ansible_password: lab123
          ansible_network_os: junipernetworks.junos.junos
          ansible_connection: netconf
        vQFX2:
          ansible_host: 192.168.100.22
          ansible_user: lab
          ansible_password: lab123
          ansible_network_os: junipernetworks.junos.junos
          ansible_connection: netconf
