---
all:
  children:
    vmx:
      hosts:
        vMX1:
          ansible_host: 192.168.100.11
          ansible_user: lab
          ansible_password: lab123
          ansible_network_os: junos
          ansible_connection: netconf
          loopback_ip: 1.1.1.1
          interface_ip: 192.168.12.1

        vMX2:
          ansible_host: 192.168.100.12
          ansible_user: lab
          ansible_password: lab123
          ansible_network_os: junos
          ansible_connection: netconf
          loopback_ip: 2.2.2.2
          interface_ip: 192.168.12.2

        vMX3:
          ansible_host: 192.168.100.13
          ansible_user: lab
          ansible_password: lab123
          ansible_network_os: junos
          ansible_connection: netconf
          loopback_ip: 3.3.3.3
          interface_ip: 192.168.12.3

    vqfx:
      hosts:
        vQFX1:
          ansible_host: 192.168.100.1
          ansible_user: lab
          ansible_password: lab123
          ansible_network_os: junos
          ansible_connection: netconf

        vQFX2:
          ansible_host: 192.168.100.2
          ansible_user: lab
          ansible_password: lab123
          ansible_network_os: junos
          ansible_connection: netconf
