---
- name: Verify BGP Community
  hosts: vMX1
  connection: netconf
  gather_facts: no
  tasks:
    - name: Check advertised BGP route
      junipernetworks.junos.junos_command:
        commands:
          - show route advertising-protocol bgp 2.2.2.2 192.168.100.0/24 extensive
      register: community_output

    - name: Display result
      debug:
        var: community_output.stdout_lines

    - name: Assert community present
      assert:
        that: "'64512:100' in community_output.stdout[0]"
