---
- name: Show OSPF neighbors
  hosts: vmx
  connection: netconf
  gather_facts: no

  tasks:
    - name: Run show ecmp route
      junipernetworks.junos.junos_command:
        commands:
          - show route 192.168.100.0/24
      register: route_output

    - name: Display result
      debug:
        var: route_output.stdout_lines