---
- name: Challenge 16 - GRE over IPsec
  hosts: vsrx
  connection: netconf
  gather_facts: no

  tasks:

    - name: configure GRE interfaces vSRX1
      junipernetworks.junos.junos_config:
        lines:
          - set interfaces gr-0/0/0 unit 0 tunnel source 172.10.10.2
          - set interfaces gr-0/0/0 unit 0 tunnel destination 172.10.30.3
          - set interfaces gr-0/0/0 unit 0 family inet address 10.10.10.1/30
      when: inventory_hostname == 'vSRX1'

    - name: configure GRE interfaces vSRX2
      junipernetworks.junos.junos_config:
        lines:
          - set interfaces gr-0/0/0 unit 0 tunnel source 172.10.30.2
          - set interfaces gr-0/0/0 unit 0 tunnel destination 172.10.10.2
          - set interfaces gr-0/0/0 unit 0 family inet address 10.10.10.2/30
      when: inventory_hostname == 'vSRX2'

    - name: configure security zones
      junipernetworks.junos.junos_config:
        lines:
          - set security zones security-zone GRE interfaces gr-0/0/0.0 host-inbound-traffic system-services all
          - set security zones security-zone GRE interfaces gr-0/0/0.0 host-inbound-traffic protocols all

    - name: configure ike phase 1 vSRX1
      junipernetworks.junos.junos_config:
        lines:
          - set security ike proposal IKE-PROP authentication-method pre-shared-keys
          - set security ike proposal IKE-PROP dh-group group14
          - set security ike proposal IKE-PROP authentication-algorithm sha-256
          - set security ike proposal IKE-PROP encryption-algorithm aes-256-cbc
          - set security ike proposal IKE-PROP lifetime-seconds 3600

    - name: configure ike phase 1 - deel 2
      junipernetworks.junos.junos_config:
        lines:
          - set security ike policy IKE-POL mode main
          - set security ike policy IKE-POL proposals IKE-PROP
          - set security ike policy IKE-POL pre-shared-key ascii-text geheim123

    - name: configure ike phase 1 vSRX1 - deel 3
      junipernetworks.junos.junos_config:
        lines:
          - set security ike gateway GW-IPSEC address 172.10.30.2
          - set security ike gateway GW-IPSEC external-interface ge-0/0/1
          - set security ike gateway GW-IPSEC ike-policy IKE-POL
      when: inventory_hostname == 'vSRX1'

    - name: configure ike phase 1 vSRX2 - deel 3
      junipernetworks.junos.junos_config:
        lines:
          - set security ike gateway GW-IPSEC address 172.10.10.2
          - set security ike gateway GW-IPSEC external-interface ge-0/0/1
          - set security ike gateway GW-IPSEC ike-policy IKE-POL
      when: inventory_hostname == 'vSRX2'

    - name: configure ipsec phase 2
      junipernetworks.junos.junos_config:
        lines:
          - set security ipsec proposal IPSEC-PROP protocol esp
          - set security ipsec proposal IPSEC-PROP authentication-algorithm hmac-sha-256-128
          - set security ipsec proposal IPSEC-PROP encryption-algorithm aes-256-cbc
          - set security ipsec policy IPSEC-POL perfect-forward-secrecy keys group14
          - set security ipsec policy IPSEC-POL proposals IPSEC-PROP

    - name: configure ipsec phase 2 vSRX1
      junipernetworks.junos.junos_config:
        lines:
          - set security ipsec vpn GRE-IPSEC bind-interface st0
          - set security ipsec vpn GRE-IPSEC ike gateway GW-IPSEC
          - set security ipsec vpn GRE-IPSEC ike ipsec-policy IPSEC-POL
          - set security ipsec vpn GRE-IPSEC traffic-selector GRE-TRAFFIC local-ip 172.10.10.2/32 remote-ip 172.10.30.2/32
      when: inventory_hostname == 'vSRX1'

    - name: configure ipsec phase 2 vSRX2
      junipernetworks.junos.junos_config:
        lines:
          - set security ipsec vpn GRE-IPSEC bind-interface st0
          - set security ipsec vpn GRE-IPSEC ike gateway GW-IPSEC
          - set security ipsec vpn GRE-IPSEC ike ipsec-policy IPSEC-POL
          - set security ipsec vpn GRE-IPSEC traffic-selector GRE-TRAFFIC local-ip 172.10.30.2/32 remote-ip 172.10.10.2/32
      when: inventory_hostname == 'vSRX2'
